export default {
  FETCH_TASK_REQUEST: "FETCH_TASK_REQUEST",
  FETCH_TASK_SUCCESS: "FETCH_TASK_SUCCESS",
  FETCH_TASK_FAILED: "FETCH_TASK_FAILED",
  FILTER_TASK_REQUEST: "FILTER_TASK_REQUEST",
  FILTER_TASK_SUCCESS: "FILTER_TASK_SUCCESS",
  ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_FAILED: "ADD_TASK_FAILED",
  EDIT_TASK_REQUEST: "EDIT_TASK_REQUEST",
  EDIT_TASK_SUCCESS: "EDIT_TASK_SUCCESS",
};
