export default {
  FETCH_TASK_REQUEST: "FETCH_TASK_REQUEST",
  FETCH_TASK_RESET: "FETCH_TASK_RESET",
  FETCH_TASK_SUCCESS: "FETCH_TASK_SUCCESS",
  FETCH_TASK_FAILED: "FETCH_TASK_FAILED",
  FILTER_TASK_REQUEST: "FILTER_TASK_REQUEST",
  FILTER_TASK_SUCCESS: "FILTER_TASK_SUCCESS",
};
