export default {
  FETCH_TASK_RESET: "FETCH_TASK_RESET",
  FETCH_TASK_SUCCESS: "FETCH_TASK_SUCCESS",
  FETCH_TASK_FAILED: "FETCH_TASK_FAILED",
  FETCH_TASK_FAILED_MESSAGE: "Error while fetching data",
};
